### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by Maclenn77**
# Hi, Microverse team:

@ShadyShawkat and me finalize the capstone project. Some details about the features:

### Home page

 When the page loads, the webapp retrieves data from:
 -  The Poké API and shows the list of items on screen.
 -  The Involvement API to show the item likes.
  The page make only 2 requests:
 -  One to the Poké API.
 -  And one to the Involvement API.

**Other features**

-  When the user clicks on the Like button of an item, the interaction is recorded in the Involvement API and the screen is updated.
-  When the user clicks on the "Comments" button, the Comments popup appears.

### Comments popup

When the popup loads, the webapp retrieves data from:

-  The Poké API and shows details about the selected item.
 -  The Involvement API to show the item comments.
   
When the user clicks on the "Comment" button, the data is recorded in the Involvement API and the screen is updated.

### Special features

- Added pagination on Homepage
- Added validation on popup
    
### Live demo and presentation

Try the [demo](https://maclenn77.github.io/Capstone-Project-JavaScript/) and check the [presentation](https://maclenn77.github.io/Capstone-Project-JavaScript/) of all the changes 

### More info

You can check more details about the project on the readme file of the [development branch](https://github.com/Maclenn77/Capstone-Project-JavaScript/). 

:snowflake: :snowman_with_snow: **Cheers and Happy Holidays !!!** :christmas_tree: :tada:

### CODE REVIEW

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
Hi @ShadyShawkat  and @Maclenn77 

Great work on making the project requirements 👏 
You've done well implementing some of the project requirements, but there are still some which aren't addressed yet, please work on it and ask for another review.

Highlights:

- The project is running successfully
- You have a descriptive Readme file
- You have implemented almost all requirements.
- All tests are passing successfully.
- You have descriptive PR
- You have a great UI, I liked it.
      
 ## Required Changes ♻️

- Project should use ES6. There are some functions that have to be changed or modified with ES6 or arrow functions instead of functions. Kindly implement it.

- You should use async and await with the fetch method to send and receive data.

## Optional suggestions

- n/a

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by Maclenn77** [comment]
Hi, @Emmyn5600 

Thanks for your comments! I'm glad that you liked the UI.

We have addressed the issues that you pointed out. So, a resume of the changes:

- [x] Functions declared with `function` keyword were refactored to arrow functions.
- [x] Functions fetching data with promises instead of `async` and `await` were refactored to use `async` and `await`.

Tested the site after that and everything is working fine. Thanks for your observations to improve this project!

Have a deserved rest on this winter break! :snowflake: :snowman_with_snow: :

**Review by mikethreels — APPROVED** [review]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 :
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Maclenn77** [comment]
Thanks, @mikethreels ! This is a great Christmas gift! :gift: 

Have a good day!

**Pull request merged**
